---
- name: Create Welcome message for multiple users using Jinja2 template
  hosts: webservers
  tasks:
    - name: Jinja2 template example
      ansible.builtin.template:
        src: ~/RHCE/real_template.j2
        dest: "{{ item.dest }}"
      loop:
        - { user: "Cash", dest: /home/Cash/newer.txt }
        - { user: "Oben", dest: /home/Oben/greater.txt }
        - { user: "Musa", dest: /home/Musa/great.txt }
        - { user: "{{ ansible_facts['user_id'] }}", dest: "/{{ ansible_facts['user_id'] }}/greener.txt" }
      vars:
        user: "{{ item.user }}"
