---
- name: Install base services
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ base_services }}"

- name: Start and enable base services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - named
    - httpd
    - firewalld

- name: Set firewall rules
  ansible.builtin.firewalld:
    port: "{{ http_port }}/tcp"
    immediate: yes
    permanent: yes
    state: enabled
